spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(YCfCLoIPjvK+J9BapEhGl0ziE40G2S505mE7y9bF3TEZd85eVXyQ6frALMwgw3N1oKoD2dOpSW1+5vFTynWbA1bU+MwC2upz4F9fjO7OTSp5iB4jjz+kp6sDd2n2DYkxoePKzB9B1faejXBnZ6BODw==)
    username: admin
    password: ENC(+ozeDPtMMKMg2CpvY4FHY/w8h2lyYUtb)

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(nByHugM5cVyzCoGWtB7fivRjl/DHS2nNlatDZtY/b5E=)
    password: ENC(Ab/pF8aVcf/pUOJXUvSQS1gQV8EixUsT7Wg+IEBZ2UA=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
---

spring:
  config:
    activate:
      on-profile: "test"


---

spring:
  config:
    activate:
      on-profile: "prod"
